/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * electronics.java
 *
 * Created on Aug 23, 2017, 2:52:54 PM
 */

/**
 *
 * @author Sushant
 */
public class electronics extends javax.swing.JFrame {
    private double Listprice;

    /** Creates new form electronics */
    public electronics() {
        initComponents();
        txtDiscount.setEnabled(false);
        txtLPrice.setEnabled(false);
        txtNPrice.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        productCb = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        optFest = new javax.swing.JRadioButton();
        optNFest = new javax.swing.JRadioButton();
        cmdList = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmdDisc = new javax.swing.JButton();
        cmdNet = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        txtLPrice = new javax.swing.JTextField();
        txtDiscount = new javax.swing.JTextField();
        txtNPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NAVNEET ELECTRONICS");

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 36));
        jLabel1.setText("Customer discount");

        jLabel2.setFont(new java.awt.Font("Andalus", 3, 18));
        jLabel2.setText("Product name");

        productCb.setFont(new java.awt.Font("Tahoma", 1, 14));
        productCb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Washing Machine", "Color Television", "Refrigerator", "OTG", "CD Player" }));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CHOOSE A TYPE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        buttonGroup1.add(optFest);
        optFest.setFont(new java.awt.Font("Andalus", 1, 18));
        optFest.setText("Festival");

        buttonGroup1.add(optNFest);
        optNFest.setFont(new java.awt.Font("Andalus", 1, 18));
        optNFest.setText("Non-Festival");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(optNFest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optFest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optFest)
                .addGap(18, 18, 18)
                .addComponent(optNFest)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        cmdList.setFont(new java.awt.Font("Times New Roman", 1, 24));
        cmdList.setText("List Price");
        cmdList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdListActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 18));
        jLabel3.setText("List Price");

        jLabel4.setFont(new java.awt.Font("Andalus", 1, 18));
        jLabel4.setText("Discount Price");

        jLabel5.setFont(new java.awt.Font("Andalus", 1, 18));
        jLabel5.setText("Net Price");

        cmdDisc.setFont(new java.awt.Font("Times New Roman", 1, 24));
        cmdDisc.setText("Discount Price");
        cmdDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDiscActionPerformed(evt);
            }
        });

        cmdNet.setFont(new java.awt.Font("Times New Roman", 1, 24));
        cmdNet.setText("Net Price");
        cmdNet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNetActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Times New Roman", 1, 24));
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        txtLPrice.setDisabledTextColor(new java.awt.Color(51, 0, 0));
        txtLPrice.setSelectedTextColor(new java.awt.Color(51, 0, 51));
        txtLPrice.setSelectionColor(new java.awt.Color(51, 0, 51));

        txtDiscount.setDisabledTextColor(new java.awt.Color(51, 0, 0));
        txtDiscount.setSelectedTextColor(new java.awt.Color(51, 0, 51));
        txtDiscount.setSelectionColor(new java.awt.Color(51, 0, 51));

        txtNPrice.setDisabledTextColor(new java.awt.Color(51, 0, 0));
        txtNPrice.setSelectedTextColor(new java.awt.Color(51, 0, 51));
        txtNPrice.setSelectionColor(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(productCb, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmdNet, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(cmdList, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(cmdDisc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNPrice, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiscount)
                                    .addComponent(txtLPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))))
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(440, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addComponent(cmdList, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(cmdNet, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
      System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void cmdListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdListActionPerformed
    String product=(String)productCb.getSelectedItem();
    if(product.equals("Washing Machine"))
    {txtLPrice.setText("12000");}
    else if(product.equals("Color Television"))
    {txtLPrice.setText("17000");}
    else if(product.equals("Refrigerator"))
    {txtLPrice.setText("18000");}
     if(product.equals("OTG"))
    {txtLPrice.setText("8000");}
     if(product.equals("CD Player"))
    {txtLPrice.setText("14500");}
    }//GEN-LAST:event_cmdListActionPerformed

    private void cmdDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDiscActionPerformed
    double discount=0,Lprice=0;
    Lprice=Double.parseDouble(txtLPrice.getText());
    if(optNFest.isSelected())
    {discount=Lprice*0.10;}
    else if(optFest.isSelected())
    {discount=Lprice*0.17;}
    txtDiscount.setText(""+discount);
    }//GEN-LAST:event_cmdDiscActionPerformed

    private void cmdNetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNetActionPerformed
      double discPrice,netamt,listprice;
      listprice=Double.parseDouble(txtLPrice.getText());
      discPrice=Double.parseDouble(txtDiscount.getText());
      netamt=listprice-discPrice;
      txtNPrice.setText(""+netamt);

    }//GEN-LAST:event_cmdNetActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new electronics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cmdDisc;
    private javax.swing.JButton cmdList;
    private javax.swing.JButton cmdNet;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton optFest;
    private javax.swing.JRadioButton optNFest;
    private javax.swing.JComboBox productCb;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtLPrice;
    private javax.swing.JTextField txtNPrice;
    // End of variables declaration//GEN-END:variables

}
