/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * kiddieland.java
 *
 * Created on Oct 29, 2017, 2:17:31 PM
 */

/**
 *
 * @author Sushant
 */
public class kiddieland extends javax.swing.JFrame {

    /** Creates new form kiddieland */
    public kiddieland() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        calcdiscountBtn = new javax.swing.JButton();
        calcnetamtBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        billTf = new javax.swing.JTextField();
        offerTf = new javax.swing.JTextField();
        addofferTf = new javax.swing.JTextField();
        netamtTf = new javax.swing.JTextField();
        platinumRbtn = new javax.swing.JRadioButton();
        silverRbtn = new javax.swing.JRadioButton();
        goldRbtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KIDDIE LAND");

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 18));
        jLabel1.setText("NAME OF CUSTOMER-");

        jLabel2.setFont(new java.awt.Font("Andalus", 1, 18));
        jLabel2.setText("BILL AMOUNT-");

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 18));
        jLabel3.setText("MODES OF PAYMENT-");

        jLabel4.setFont(new java.awt.Font("Andalus", 1, 18));
        jLabel4.setText("OFFER-");

        jLabel5.setFont(new java.awt.Font("Andalus", 1, 18));
        jLabel5.setText("ADDITIONAL OFFER-");

        jLabel6.setFont(new java.awt.Font("Andalus", 1, 18));
        jLabel6.setText("NET AMOUNT-");

        calcdiscountBtn.setFont(new java.awt.Font("Arial", 1, 18));
        calcdiscountBtn.setText("CALCULATE DISCOUNT");
        calcdiscountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcdiscountBtnActionPerformed(evt);
            }
        });

        calcnetamtBtn.setFont(new java.awt.Font("Arial", 1, 18));
        calcnetamtBtn.setText("CALCULATE NET AMOUNT");
        calcnetamtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcnetamtBtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Arial", 1, 18));
        exitBtn.setText("EXIT");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(platinumRbtn);
        platinumRbtn.setFont(new java.awt.Font("Arial", 1, 14));
        platinumRbtn.setText("PLATINUM");

        buttonGroup1.add(silverRbtn);
        silverRbtn.setFont(new java.awt.Font("Arial", 1, 14));
        silverRbtn.setText("SILVER");

        buttonGroup1.add(goldRbtn);
        goldRbtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        goldRbtn.setText("GOLD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(calcdiscountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(calcnetamtBtn)
                        .addGap(83, 83, 83)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                                    .addGap(101, 101, 101))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(64, 64, 64)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(netamtTf, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                    .addComponent(addofferTf, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                    .addComponent(offerTf, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                    .addComponent(billTf, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                                .addGap(201, 201, 201))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(platinumRbtn)
                                .addGap(69, 69, 69)
                                .addComponent(silverRbtn)
                                .addGap(84, 84, 84)
                                .addComponent(goldRbtn)
                                .addGap(69, 69, 69)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(211, 211, 211))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billTf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(platinumRbtn)
                            .addComponent(silverRbtn)
                            .addComponent(goldRbtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(offerTf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(netamtTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(addofferTf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(calcnetamtBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(calcdiscountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
    System.exit(0);
}//GEN-LAST:event_exitBtnActionPerformed

    private void calcdiscountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcdiscountBtnActionPerformed
double bill=0,offer=0,addoffer=0;
bill=Double.parseDouble(billTf.getText());
if (bill>25000){
    addoffer=bill*.05;}
if(platinumRbtn.isSelected())
{offer=bill*.02;}
if(goldRbtn.isSelected())
{offer=bill*.15;}
if(silverRbtn.isSelected())
{offer=bill*.01;}
offerTf.setText(""+offer);
addofferTf.setText(""+addoffer);


}//GEN-LAST:event_calcdiscountBtnActionPerformed

    private void calcnetamtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcnetamtBtnActionPerformed
       double billamt=0,offeramt=0,adofferamt=0,netamt=0;
       billamt=Double.parseDouble(billTf.getText());
       offeramt=Double.parseDouble(offerTf.getText());
       adofferamt=Double.parseDouble(addofferTf.getText());
       netamt=billamt-offeramt-adofferamt;
       netamtTf.setText(""+netamt);
    }//GEN-LAST:event_calcnetamtBtnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kiddieland().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addofferTf;
    private javax.swing.JTextField billTf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calcdiscountBtn;
    private javax.swing.JButton calcnetamtBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JRadioButton goldRbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField netamtTf;
    private javax.swing.JTextField offerTf;
    private javax.swing.JRadioButton platinumRbtn;
    private javax.swing.JRadioButton silverRbtn;
    // End of variables declaration//GEN-END:variables

}
